name: Docker Image CI

on:
  push:
    branches: [ "tc" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: azure/docker-login@v1
      with:
        login-server: millo.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t millo.azurecr.io/fastinf:${{ github.sha }}
        docker push millo.azurecr.io/fastinf:${{ github.sha }}


